fix: update-agent build (#306)
The build fails with error:

> error[E0599]: the method `as_dyn_error` exists for reference `&Error`, but its trait bounds were not satisfied
>   --> update-agent/core/src/pubkeys.rs:76:21
>    |
> 76 |     InvalidPubKey(#[from] SignatureError),
>    |                     ^^^^ method cannot be called on `&Error` due to unsatisfied trait bounds
>    |
>   ::: /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/signature-2.2.0/src/error.rs:26:1
>    |
> 26 | pub struct Error {
>    | ---------------- doesn't satisfy `ed25519_dalek::ed25519::Error: AsDynError<'_>` or `ed25519_dalek::ed25519::Error: StdError`
>    |
>    = note: the following trait bounds were not satisfied:
>            `ed25519_dalek::ed25519::Error: StdError`
>            which is required by `ed25519_dalek::ed25519::Error: AsDynError<'_>`
>            `&ed25519_dalek::ed25519::Error: StdError`
>            which is required by `&ed25519_dalek::ed25519::Error: AsDynError<'_>`

That happens because `ed25519_dalek::SignatureError` implements
`std::error::Error` only if flag `std` is enabled [1]

[1] https://docs.rs/ed25519-dalek/latest/ed25519_dalek/type.SignatureError.html#impl-Error-for-Error